# Generated by Django 3.1.7 on 2021-06-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='CorProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_produto', models.CharField(max_length=50, unique=True, verbose_name='Cor do produto')),
            ],
            options={
                'ordering': ['cor_produto'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=50, verbose_name='Nome do fornecedor')),
                ('nome_fornecedor_redizido', models.CharField(max_length=50, verbose_name='Nome reduzido')),
                ('cnpj_fornecedor', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('logradouro_fornecedor', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('numero_via_fornecedor', models.IntegerField(verbose_name='Número da via')),
                ('cidade_fornecedor', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf_fornecedor', models.CharField(max_length=2, verbose_name='UF')),
                ('contato_fornecedor', models.CharField(max_length=255, verbose_name='Contato do fornecedor')),
                ('email_fornecedor', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone_fornecedor', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_produto', models.CharField(max_length=50, unique=True, verbose_name='Tamanho do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do produto')),
                ('descricao_produto', models.CharField(blank=True, max_length=255, verbose_name='Descrição do produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço unitário')),
                ('quantidade_disponivel', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade disponível')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (Kg)')),
                ('ncm', models.CharField(max_length=12, verbose_name='NCM')),
                ('localizacao', models.CharField(max_length=11, verbose_name='Localização no Estoque')),
                ('estoque_minimo', models.PositiveIntegerField(verbose_name='Estoque mínimo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do produto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.categoria')),
                ('cor_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.corproduto', verbose_name='Cor do produto')),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.fornecedor', verbose_name='Fornecedor')),
                ('tamanho_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.tamanhoproduto', verbose_name='Tamanho')),
            ],
        ),
    ]
