# Generated by Django 3.1.7 on 2021-03-26 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_produto', models.CharField(max_length=50, verbose_name='Cor do produto')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.CharField(max_length=50, verbose_name='Status do pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='TamanhoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_produto', models.CharField(max_length=50, verbose_name='Tamanho do produto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(max_length=50, verbose_name='Tipo de movimentação')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor do pedido')),
                ('data_pedido', models.DateField(auto_now=True, verbose_name='Data da abertura')),
                ('data_fechamento', models.DateField(verbose_name='Data do fechamento')),
                ('frete', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Valor do frete')),
                ('nota_fiscal', models.IntegerField(verbose_name='Numero da nota fiscal')),
                ('pedido_ususario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.statuspedido', verbose_name='Status')),
                ('tipo_movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipomovimentacao', verbose_name='Movimentação')),
            ],
        ),
    ]
