# Generated by Django 3.1.7 on 2021-04-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_fechamento',
            field=models.DateField(blank=True, verbose_name='Data do fechamento'),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do produto')),
                ('descricao_produto', models.CharField(blank=True, max_length=255, verbose_name='Descrição do produto')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço unitário')),
                ('quantidade_disponivel', models.IntegerField(verbose_name='Quantidade disponíve')),
                ('cor_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.corproduto', verbose_name='Cor do produto')),
                ('tamanho_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.tamanhoproduto', verbose_name='Tamanho do produto')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_item', models.IntegerField(verbose_name='Quantidade de produtos')),
                ('desconto', models.DecimalField(blank=True, decimal_places=4, max_digits=5, verbose_name='Desconto')),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor do item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pedido', verbose_name='Pedido N.')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto')),
            ],
        ),
    ]
