# Generated by Django 3.1.7 on 2021-04-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20210403_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço unitário'),
        ),
    ]
