# Generated by Django 3.1.7 on 2021-05-01 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20210404_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corproduto',
            options={'ordering': ['cor_produto']},
        ),
    ]
