# Generated by Django 3.1.7 on 2021-05-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20210430_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_ususario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='status_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_movimentacao',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='StatusPedido',
        ),
        migrations.DeleteModel(
            name='TipoMovimentacao',
        ),
    ]
