# Generated by Django 3.1.7 on 2021-05-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
