# Generated by Django 3.1.7 on 2021-05-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_auto_20210516_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(max_length=11, verbose_name='Localização no Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(max_length=10, verbose_name='NCM'),
        ),
    ]
