# Generated by Django 3.1.7 on 2021-05-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20210516_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=50, verbose_name='Nome do fornecedor')),
                ('nome_fornecedor_redizido', models.CharField(max_length=50, verbose_name='Nome reduzido')),
                ('cnpj_fornecedor', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('logradouro_fornecedor', models.CharField(max_length=50, verbose_name='Logradouro')),
                ('numero_via_fornecedor', models.IntegerField(verbose_name='Número da via')),
                ('cidade_fornecedor', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf_fornecedor', models.CharField(max_length=2, verbose_name='UF')),
                ('contato_fornecedor', models.CharField(max_length=255, verbose_name='Contato do fornecedor')),
                ('email_fornecedor', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone_fornecedor', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
