# Generated by Django 3.1.7 on 2021-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_auto_20210519_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(max_length=11, verbose_name='NCM'),
        ),
    ]
