# Generated by Django 3.1.7 on 2021-06-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_auto_20210519_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(verbose_name='Quantidade disponível'),
        ),
    ]
