# Generated by Django 3.1.7 on 2021-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20210601_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade disponível'),
        ),
    ]
