# Generated by Django 3.1.7 on 2021-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_auto_20210603_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade disponível'),
        ),
    ]
