# Generated by Django 3.1.7 on 2021-06-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_auto_20210603_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Preço unitário'),
            preserve_default=False,
        ),
    ]
