# Generated by Django 3.1.7 on 2021-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOTAL_PRODUTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField()),
                ('CREATED', models.DateTimeField()),
                ('NOME_PRODUTO', models.CharField(max_length=50)),
                ('QUANTIDADE', models.PositiveIntegerField()),
                ('MOVIMENTO', models.CharField(max_length=50)),
                ('TOTAL', models.FloatField()),
            ],
            options={
                'db_table': 'TOTAL_PRODUTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-id'],
            },
        ),
    ]
