# Generated by Django 3.1.7 on 2021-05-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
