# Generated by Django 3.1.7 on 2021-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relatorio', '0002_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTAL_PRODUTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_MOVIMENO', models.DateTimeField()),
                ('PROTUDO', models.CharField(max_length=50)),
                ('QUANTIDADE', models.PositiveIntegerField()),
                ('MOVIMENTO', models.CharField(max_length=50)),
                ('TOTAL', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'TOTAL_PRODUTOS',
                'managed': False,
            },
        ),
    ]
