# Generated by Django 3.1.7 on 2021-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_auto_20210526_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESULTADO_FINANC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.PositiveIntegerField()),
                ('RESULT', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'RESULTADO_FINANC',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RESUMO_FINANC',
        ),
    ]
