# Generated by Django 3.1.7 on 2021-05-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_totalizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESUMO_FINANC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESULTADO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'RESUMO_FINANC',
                'managed': False,
            },
        ),
    ]
