# Generated by Django 3.1.7 on 2021-06-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota Fiscal *')),
                ('movimento', models.CharField(choices=[('e', 'entrada'), ('s', 'saida'), ('b', 'baixa')], max_length=1)),
                ('nf_arquivo', models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='NF. Arquivo *')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Qtd.: ')),
                ('saldo', models.PositiveIntegerField(verbose_name='Estoque: ')),
                ('preco_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='R$/Unid.')),
                ('valor_item', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total(R$)')),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('justificativa_baixa', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.estoque', verbose_name='Item')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.produto', verbose_name='Produto: ')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
