# Generated by Django 3.1.7 on 2021-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20210508_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
