# Generated by Django 3.1.7 on 2021-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_estoqueitens_preco_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='valor_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
