# Generated by Django 3.1.7 on 2021-05-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_auto_20210508_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
