# Generated by Django 3.1.7 on 2021-05-10 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20210508_1600'),
        ('estoque', '0008_auto_20210508_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produto', verbose_name='Produto: '),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Qtd.: '),
        ),
    ]
