# Generated by Django 3.1.7 on 2021-05-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_auto_20210509_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='valor_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
