# Generated by Django 3.1.7 on 2021-05-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_auto_20210511_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='valor_item_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
