# Generated by Django 3.1.7 on 2021-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_auto_20210511_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='valor_item_total',
        ),
        migrations.AddField(
            model_name='estoque',
            name='valor_item_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='R$/Unid.'),
        ),
    ]
