# Generated by Django 3.1.7 on 2021-05-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_auto_20210513_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='valor_item_total',
        ),
    ]
