# Generated by Django 3.1.7 on 2021-05-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20210515_1201'),
        ('estoque', '0014_remove_estoque_valor_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastros.produto', verbose_name='Produto: '),
        ),
    ]
