# Generated by Django 3.1.7 on 2021-05-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20210515_1201'),
        ('estoque', '0018_auto_20210515_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto', verbose_name='Produto: '),
        ),
    ]
