# Generated by Django 3.1.7 on 2021-05-15 15:54

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20210515_1201'),
        ('estoque', '0020_auto_20210515_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=models.SET(cadastros.models.Produto), to='cadastros.produto', verbose_name='Produto: '),
        ),
    ]
