# Generated by Django 3.1.7 on 2021-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_auto_20210515_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='nf_arquivo',
            field=models.FileField(default=0, upload_to='notas_fiscais/'),
            preserve_default=False,
        ),
    ]
