# Generated by Django 3.1.7 on 2021-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_auto_20210516_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nf_arquivo',
            field=models.FileField(default=1, upload_to='notas_fiscais/'),
            preserve_default=False,
        ),
    ]
