# Generated by Django 3.1.7 on 2021-05-17 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20210516_2252'),
        ('estoque', '0026_auto_20210516_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='cadastros.produto'),
            preserve_default=False,
        ),
    ]
