# Generated by Django 3.1.7 on 2021-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_auto_20210516_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='fabricante',
            field=models.CharField(default=1, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
