# Generated by Django 3.1.7 on 2021-05-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_estoqueitens_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='categoria',
        ),
    ]
