# Generated by Django 3.1.7 on 2021-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_auto_20210519_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueBaixa',
            fields=[
            ],
            options={
                'verbose_name': 'estoque baixa',
                'verbose_name_plural': 'estoque baixa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.estoque',),
        ),
        migrations.AddField(
            model_name='estoqueitens',
            name='justificativa_baixa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Justificativa para baixa no estoque'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(choices=[('e', 'entrada'), ('s', 'saida'), ('b', 'baixa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='nf_arquivo',
            field=models.FileField(upload_to='notas_fiscais/', verbose_name='Arquivo - Nota Fiscal'),
        ),
    ]
