# Generated by Django 3.1.7 on 2021-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_auto_20210522_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nf',
            field=models.PositiveIntegerField(default='0', verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='nf_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='notas_fiscais/', verbose_name='NF. Arquivo'),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='justificativa_baixa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
