# Generated by Django 3.1.7 on 2021-05-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_auto_20210521_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='justificativa_baixa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Justificativa para baixa no estoque'),
        ),
    ]
