# Generated by Django 3.1.7 on 2021-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_auto_20210524_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nf_arquivo',
            field=models.FileField(default=1, upload_to='notas_fiscais/', verbose_name='NF. Arquivo'),
            preserve_default=False,
        ),
    ]
