# Generated by Django 3.1.7 on 2021-05-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_auto_20210524_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nf',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota Fiscal'),
        ),
    ]
