# Generated by Django 3.1.7 on 2021-06-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_auto_20210524_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='nf',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='valor_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Total(R$)'),
        ),
    ]
