# Generated by Django 3.1.7 on 2021-06-01 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_auto_20210601_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
    ]
