# Generated by Django 3.1.7 on 2021-06-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0037_auto_20210603_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9, verbose_name='R$/Unid.'),
            preserve_default=False,
        ),
    ]
