# Generated by Django 3.1.7 on 2021-06-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0038_auto_20210603_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='R$/Unid.'),
        ),
    ]
