# Generated by Django 2.0.13 on 2021-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='data de registro')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='ultimo login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
