# Generated by Django 3.1.7 on 2021-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210321_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=999999999999999, max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
